services:
  api:
    image: hue-api:latest
    ports:
      - 8080:8080
    command: -configFilePath ./config.json
    volumes:
      - type: bind
        source: ./config.json
        target: /home/app/config.json