services:
  api:
    image: ghcr.io/bongofriend/hue-api:v1.0.0
    ports:
      - 8080:8080
    command: -configFilePath ./config.json
    volumes:
      - type: bind
        source: ./config.json
        target: /home/app/config.json