services:
  api:
    build:
      context: .
    ports:
      - 8080:8080
    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    command: -configFilePath ./config.json
    volumes:
      - type: bind
        source: ./config.json
        target: /home/app/config.json